### Signup FARMER
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "admin",
  "role": "ADMIN",
  "name": "admin",
  "phone": "++33600000000",
  "location": "Lyon"
}

### Signup WORKER
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "email": "worker@test.com",
  "password": "azerty123",
  "role": "WORKER",
  "name": "Alice Travailleuse",
  "phone": "+2420000002",
  "location": "Brazzaville"
}

### Login Worker
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "worker@test.com",
  "password": "azerty123"
}

### Login Farmer
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "farmer@test.com",
  "password": "12345678"
}

### Login Unexisting e-mail
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "worker@testing.com",
  "password": "azerty123"
}

###Secure with Auth test should fail
GET http://localhost:3000/api/auth/me
Authorization: Bearer <VOTRE_JWT>


###Secure with Auth test 
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmMDM4M2M2LTViYWQtNGViMi1iMjcyLTFkNjBmMzNhNzk1ZCIsInJvbGUiOiJXT1JLRVIiLCJpYXQiOjE3NTAyMDIxNTQsImV4cCI6MTc1MDI4ODU1NH0.V9lNQCwPNZUx4i2ex8lRGag8Ufyu0jS3PjEV1vGJ1iY

###Post a job as FARMER
POST http://localhost:3000/api/jobs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc5MTIzOTVhLTFjYzUtNDJkNS05MzQ1LTc4OGJiYmQzOTUzOSIsInJvbGUiOiJGQVJNRVIiLCJpYXQiOjE3NTAyMDMyMzcsImV4cCI6MTc1MDI4OTYzN30.E-G29b7a8DNw0WUV7m2gUiSzL5_Qs-uGnC9Ve3sWq60
Content-Type: application/json

{
  "title": "Récolte de manioc",
  "description": "Nous recherchons 3 travailleurs pour 2 jours de récolte.",
  "location": "Brazzaville"
}

###Post a second job as FARMER
POST http://localhost:3000/api/jobs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc5MTIzOTVhLTFjYzUtNDJkNS05MzQ1LTc4OGJiYmQzOTUzOSIsInJvbGUiOiJGQVJNRVIiLCJpYXQiOjE3NTAyMDMyMzcsImV4cCI6MTc1MDI4OTYzN30.E-G29b7a8DNw0WUV7m2gUiSzL5_Qs-uGnC9Ve3sWq60
Content-Type: application/json

{
  "title": "Récolte de carti",
  "description": "Nous recherchons 3 travailleurs pour 2 jours de récolte.",
  "location": "Brazzaville"
}

###Post job as Worker
POST http://localhost:3000/api/jobs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmMDM4M2M2LTViYWQtNGViMi1iMjcyLTFkNjBmMzNhNzk1ZCIsInJvbGUiOiJXT1JLRVIiLCJpYXQiOjE3NTAyMDMwNzEsImV4cCI6MTc1MDI4OTQ3MX0.BEgx7qRNDs5n5R0AV1Qrt9fkDR1KwnGRPBsFxKG533E
Content-Type: application/json

{
  "title": "Récolte de manioc",
  "description": "Nous recherchons 3 travailleurs pour 2 jours de récolte.",
  "location": "Brazzaville"
}

###GET all jobs
GET http://localhost:3000/api/jobs

### Apply to a job working version
POST http://localhost:3000/api/jobs/e5ac69b6-eedf-4f40-ae59-143c1d90d06a/apply
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmMDM4M2M2LTViYWQtNGViMi1iMjcyLTFkNjBmMzNhNzk1ZCIsInJvbGUiOiJXT1JLRVIiLCJpYXQiOjE3NTAyMDMwNzEsImV4cCI6MTc1MDI4OTQ3MX0.BEgx7qRNDs5n5R0AV1Qrt9fkDR1KwnGRPBsFxKG533E
Content-Type: application/json

{
  "message": "Disponible toute la semaine !"
}

###Get Applications
GET http://localhost:3000/api/jobs/e5ac69b6-eedf-4f40-ae59-143c1d90d06a/applications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc5MTIzOTVhLTFjYzUtNDJkNS05MzQ1LTc4OGJiYmQzOTUzOSIsInJvbGUiOiJGQVJNRVIiLCJpYXQiOjE3NTAyMDMyMzcsImV4cCI6MTc1MDI4OTYzN30.E-G29b7a8DNw0WUV7m2gUiSzL5_Qs-uGnC9Ve3sWq60

###Admin GET users
GET http://localhost:3000/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAzZjMwODgzLTU0NGQtNGFhZi1iNzE1LTY0YzE1ODdjMGQ5OSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MDIzOTYwMywiZXhwIjoxNzUwMzI2MDAzfQ.jreXuE84b8DntZrLiBdmFdbO_03RTcXklwUeLkcp5hw

###Admin GET jobs
GET http://localhost:3000/api/admin/jobs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAzZjMwODgzLTU0NGQtNGFhZi1iNzE1LTY0YzE1ODdjMGQ5OSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MDIzOTYwMywiZXhwIjoxNzUwMzI2MDAzfQ.jreXuE84b8DntZrLiBdmFdbO_03RTcXklwUeLkcp5hw
